name: MakoDev Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CAN_BUILD: true
  CAN_TEST: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ env.CAN_BUILD == true }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: src/

      - name: Upload Build Artefact
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact
          path: |
            src/bin/
            src/obj/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && env.CAN_TEST == true }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      - name: Download Build Artefact
        uses: actions/download-artifact@v2
        with:
          name: build-artefact
          path: src/

      - name: Unit Tests
        if: github.event_name == 'pull_request'
        run: dotnet test --no-build --verbosity normal --configuration Release
        working-directory: src/
