name: MakoBlog Build Pipeline

on:
  push:
    branches: [main, MakoPhil:main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: src/

      - name: Upload Build Artefact
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact
          path: |
            src/**/bin/
            src/**/obj/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      - name: Download Build Artefact
        uses: actions/download-artifact@v2
        with:
          name: build-artefact
          path: src/

      - name: Unit Tests
        run: dotnet test --no-build --verbosity normal --configuration Release
        working-directory: src/

  publish:
    name: Publish Frontend
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/

      - name: Download Build Artefact
        uses: actions/download-artifact@v2
        with:
          name: build-artefact
          path: src/

      - name: Publish Frontend
        run: dotnet publish --no-build --verbosity normal --configuration Release --runtime linux-x64 --self-contained true -p:BlazorEnableCompression=false
        working-directory: src/Client/MakoBlog/

      - name: Upload Frontend Published Artefact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-published
          path: src/Client/MakoBlog/bin/Release/net5.0/publish/wwwroot
