name: SSH Deploy to Test

on:
  workflow_run:
    workflows: ["MakoBlog Build Pipeline"]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: Test

    steps:
      - name: Download Published Client Artefact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-pipeline.yml"
          workflow_conclusion: success
          name: frontend-published
          path: '${{ github.workspace }}/deploy/'

      - name: Clear destination directory
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: "rm -rf ${{ secrets.DEPLOY_DIRECTORY }}/*"
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: SCP Files Action
        uses: a-was/scp-files-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: '${{ github.workspace }}/deploy/*'
          destination: ${{ secrets.DEPLOY_DIRECTORY }}
